ci: remove build steps to deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,48 +20,42 @@ on:
         type: string
 
 jobs:
-  build_contracts:
-    if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic", "cowboy0015"]', github.actor)
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up Rust toolchain
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          toolchain: stable
-      - name: Build Contracts
-        run: |
-          make version-map
-          make build
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: contracts
-          path: ./artifacts/
-          if-no-files-found: error
+  # build_contracts:
+  #   if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic", "cowboy0015"]', github.actor)
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Set up Rust toolchain
+  #       uses: dtolnay/rust-toolchain@stable
+  #       with:
+  #         toolchain: stable
+  #     - name: Build Contracts
+  #       run: |
+  #         make version-map
+  #         make build
 
-  build_schemas:
-    if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic", "cowboy0015"]', github.actor)
-    runs-on: ubuntu-latest
-    outputs:
-      schema_url: ${{ steps.upload-schemas.outputs.artifact-url }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Build Schemas
-        run: |
-          set -eo pipefail
-          make schemas || {
-            echo "Schema build failed"
-            exit 1
-          }
-      - name: Upload Schemas to Temp
-        id: upload-schemas
-        uses: actions/upload-artifact@v4
-        with:
-          name: temp-schemas
-          path: ./schemas/
-          retention-days: 1
-          if-no-files-found: error
+  # build_schemas:
+  #   if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic", "cowboy0015"]', github.actor)
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     schema_url: ${{ steps.upload-schemas.outputs.artifact-url }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Build Schemas
+  #       run: |
+  #         set -eo pipefail
+  #         make schemas || {
+  #           echo "Schema build failed"
+  #           exit 1
+  #         }
+  #     - name: Upload Schemas to Temp
+  #       id: upload-schemas
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: temp-schemas
+  #         path: ./schemas/
+  #         retention-days: 1
+  #         if-no-files-found: error
 
   build_deploy_script:
     if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic", "cowboy0015"]', github.actor)
@@ -77,9 +71,9 @@ jobs:
           path: ./target/release/andromeda-deploy
           if-no-files-found: error
 
-  deploy:
+  build_and_deploy:
     runs-on: ubuntu-latest
-    needs: [build_contracts, build_schemas, build_deploy_script]
+    needs: [build_deploy_script]
     env:
       DEPLOYMENT_CHAIN: ${{ inputs.network }}
       DEPLOYMENT_KERNEL_ADDRESS: ${{ inputs.kernel_address }}
@@ -108,9 +102,23 @@ jobs:
         run: |
           chmod +x ./andromeda-deploy
           ./andromeda-deploy
+      - name: Upload Contract Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: contracts
+          path: ./artifacts/
+          if-no-files-found: error
+          retention-days: 1
+      - name: Upload Schema Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: temp-schemas
+          path: ./schemas/
+          if-no-files-found: error
+          retention-days: 1
 
   trigger-schema-parser:
-    needs: [deploy]
+    needs: [build_and_deploy]
     runs-on: ubuntu-latest
     outputs:
       should_continue: ${{ steps.check-kernel.outputs.should_continue }}
