Added workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,5 +1,4 @@
 name: Deploy OS
-
 on:
   workflow_dispatch:
     inputs:
@@ -16,7 +15,7 @@ on:
         required: false
         type: boolean
       contracts:
-        description: "Contracts to deploy (e.g. splitter, validator-staking)"
+        description: "Contracts to deploy"
         required: false
         type: string
 
@@ -36,6 +35,7 @@ jobs:
           name: contracts
           path: ./artifacts/
           if-no-files-found: error
+
   build_deploy_script:
     if: contains('["crnbarr93", "SlayerAnsh", "joemonem", "DimitrijeDragasevic", "cowboy0015"]', github.actor)
     runs-on: ubuntu-latest
@@ -49,6 +49,7 @@ jobs:
           name: deploy
           path: ./target/release/andromeda-deploy
           if-no-files-found: error
+
   deploy:
     runs-on: ubuntu-latest
     needs: [build_contracts, build_deploy_script]
@@ -86,3 +87,42 @@ jobs:
           name: deployment-report
           path: ./deployment-reports/
           if-no-files-found: error
+
+  trigger-schema-parser:
+    needs: deploy
+    runs-on: ubuntu-latest
+    env:
+      NETWORK: ${{ inputs.network }}
+    steps:
+      - name: Set Branch
+        id: set-branch
+        run: |
+          if [[ "$NETWORK" == "mainnet" ]]; then
+            echo "branch=main" >> $GITHUB_OUTPUT
+          elif [[ "$NETWORK" == "testnet" ]]; then
+            echo "branch=develop" >> $GITHUB_OUTPUT
+          elif [[ "$NETWORK" == "testnet-staging" ]]; then
+            echo "branch=testnet-staging" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid network specified"
+            exit 1
+          fi
+
+      - name: Trigger Schema Parser
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.PAT_TOKEN }}
+          script: |
+            try {
+              await github.rest.actions.createWorkflowDispatch({
+                owner: 'andromedaprotocol',
+                repo: 'schema-parser',
+                workflow_id: 'process-schema.yml',
+                ref: '${{ steps.set-branch.outputs.branch }}',
+                inputs: {
+                  network: '${{ inputs.network }}'
+                }
+              });
+            } catch (error) {
+              core.setFailed(`Failed to trigger schema parser workflow: ${error.message}`);
+            }
